# Generated by Django 3.2.4 on 2021-06-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tempo_preparo', models.TimeField(verbose_name='Tempo de Preparo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('diario', models.BooleanField(default=False, verbose_name='Cardápio Diário')),
                ('destino', models.CharField(choices=[('Cozinha Fria', 'Cozinha Fria'), ('Cozinha Quente', 'Cozinha Quente'), ('Sobremesas', 'Sobremesas')], max_length=14, verbose_name='Cozinha Destino')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('Em Preparo', 'Em Preparo'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado'), ('Baixado', 'Baixado'), ('Atrasado', 'Atrasado')], default='Em Preparo', max_length=10, verbose_name='Situação')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('hora_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Hora do Pedido')),
                ('hora_situacao', models.DateTimeField(auto_now=True, verbose_name='Situação Alterada')),
                ('limite_entrega', models.TimeField(blank=True, null=True, verbose_name='Limite da Entrega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='PedidoAtrasado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_atraso', models.TimeField(blank=True, null=True, verbose_name='Tempo de Atraso')),
                ('data_atraso', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pedido Atrasado',
                'verbose_name_plural': 'Pedidos Atrasados',
            },
        ),
    ]
