# Generated by Django 3.2.4 on 2021-06-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tempo_restante',
            field=models.TimeField(blank=True, null=True, verbose_name='Tempo Restante'),
        ),
    ]
