# Generated by Django 3.2.4 on 2021-06-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_tempo_restante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='hora_entrega',
            field=models.DateTimeField(auto_now=True, verbose_name='Hora Entrega'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tempo_preparo',
            field=models.IntegerField(verbose_name='Tempo de Preparo (Min)'),
        ),
    ]
