# Generated by Django 3.2.4 on 2021-06-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210615_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tempo_preparo',
            field=models.TimeField(verbose_name='Tempo de Preparo (Min)'),
        ),
    ]
