# Generated by Django 3.2.4 on 2021-11-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_tempo_preparo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnqueteClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Resposta')),
                ('resp1', models.IntegerField(verbose_name='Nota Cozinha')),
                ('resp2', models.IntegerField(verbose_name='Nota Atendimento')),
                ('resp3', models.BooleanField(default=True, verbose_name='Recomendaria?')),
            ],
            options={
                'verbose_name': 'Enquete Cliente',
                'verbose_name_plural': 'Enquetes Clientes',
            },
        ),
        migrations.CreateModel(
            name='EnqueteFuncionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Resposta')),
                ('resp1', models.IntegerField(verbose_name='Resposta 1')),
                ('resp2', models.IntegerField(verbose_name='Resposta 2')),
                ('resp3', models.BooleanField(default=True, verbose_name='Resposta 3')),
            ],
            options={
                'verbose_name': 'Enquete Funcionários',
                'verbose_name_plural': 'Enquetes Funcionários',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='tempo_preparo',
            field=models.IntegerField(verbose_name='Tempo de Preparo (Min)'),
        ),
    ]
